/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;

/**
 *
 * @author Don OzOn
 */
public class EmployeeManagement extends javax.swing.JFrame {

    /**
     * Creates new form AddNewEmployee
     */
    public EmployeeManagement() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BTAdd = new javax.swing.JButton();
        BTSearch = new javax.swing.JButton();
        BTShow = new javax.swing.JButton();
        BTExit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Employee Management");

        BTAdd.setText("Add New");

        BTSearch.setText("Search");

        BTShow.setText("Show");

        BTExit.setText("Exit");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 144, 207));
        jLabel1.setText("EMPLOYEE MANAGEMENT");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(152, 152, 152)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTExit)
                            .addComponent(BTShow)
                            .addComponent(BTSearch)
                            .addComponent(BTAdd))))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {BTAdd, BTExit, BTSearch, BTShow});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(BTAdd)
                .addGap(18, 18, 18)
                .addComponent(BTSearch)
                .addGap(18, 18, 18)
                .addComponent(BTShow)
                .addGap(18, 18, 18)
                .addComponent(BTExit)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {BTAdd, BTExit, BTSearch, BTShow});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    public JButton getBTAdd() {
        return BTAdd;
    }

    public void setBTAdd(JButton BTAdd) {
        this.BTAdd = BTAdd;
    }

    public JButton getBTExit() {
        return BTExit;
    }

    public void setBTExit(JButton BTExit) {
        this.BTExit = BTExit;
    }

    public JButton getBTSearch() {
        return BTSearch;
    }

    public void setBTSearch(JButton BTSearch) {
        this.BTSearch = BTSearch;
    }

    public JButton getBTShow() {
        return BTShow;
    }

    public void setBTShow(JButton BTShow) {
        this.BTShow = BTShow;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTAdd;
    private javax.swing.JButton BTExit;
    private javax.swing.JButton BTSearch;
    private javax.swing.JButton BTShow;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
