/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Don OzOn
 */
public class Search extends javax.swing.JFrame {

    /**
     * Creates new form Search
     */
    public Search() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        TF_ID_Search = new javax.swing.JTextField();
        BTSearch = new javax.swing.JButton();
        BTBack = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA_ShowAll = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Search Employee");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        jLabel1.setText("Employee ID");

        BTSearch.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        BTSearch.setText("Search");

        BTBack.setText("<Back");

        TA_ShowAll.setEditable(false);
        TA_ShowAll.setColumns(20);
        TA_ShowAll.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TA_ShowAll.setRows(5);
        jScrollPane1.setViewportView(TA_ShowAll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(27, 27, 27)
                            .addComponent(TF_ID_Search, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(BTSearch))
                        .addComponent(BTBack)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TF_ID_Search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BTBack)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    public JButton getBTBack() {
        return BTBack;
    }

    /**
     * @param args the command line arguments
     */
    public void setBTBack(JButton BTBack) {
        this.BTBack = BTBack;
    }

    public JButton getBTSearch() {
        return BTSearch;
    }

    public void setBTSearch(JButton BTSearch) {
        this.BTSearch = BTSearch;
    }

    public JTextArea getTA_ShowAll() {
        return TA_ShowAll;
    }

    public void setTA_ShowAll(JTextArea TA_ShowAll) {
        this.TA_ShowAll = TA_ShowAll;
    }


    public JTextField getTF_ID_Search() {
        return TF_ID_Search;
    }

    /**
     * @param args the command line arguments
     */
    public void setTF_ID_Search(JTextField TF_ID_Search) {
        this.TF_ID_Search = TF_ID_Search;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTBack;
    private javax.swing.JButton BTSearch;
    private javax.swing.JTextArea TA_ShowAll;
    private javax.swing.JTextField TF_ID_Search;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
